#!/usr/bin/python
#	vim:fileencoding=utf-8
# Create merged 'package.mask' file and maintain 'package.unmask' using it
# (C) 2010 Michał Górny, distributed under the terms of 3-clause BSD license

import os.path, sys

try:
	from diffmask.cli import main
except ImportError:
	sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'lib'))
	# Ensure a clean reload from the new location.
	if 'diffmask' in sys.modules:
		reload(sys.modules['diffmask'])
		del sys.modules['diffmask']
	from diffmask.cli import main

if __name__ == '__main__':
	sys.exit(main(sys.argv))
